signage_players:
  vars:
    ansible_user: uucb
    signage_schedule:
      - { days: "Sun", start_time: "10:00", end_time: "13:00", url: 'rtmp://restreamer.uubloomington.org/3927bd7b-3303-4707-927d-2594a0c34135.stream?token=washing-hardiness-cathedral-void' }
    signage_browser: 'custom'
    signage_browser_package: 'vlc'
    signage_browser_command: 'retry "cvlc --play-and-exit '
    signage_browser_window_name: 'vlc'
    signage_browser_execstart_override: >
      bash -c 'retry "cvlc --play-and-exit  $(cat /var/ansible-digital-signage/current)"'
  hosts:
    display1.uubloomington.org:
    192.168.0.39:

kiosks:
  vars:
    ansible_user: uucb
    signage_schedule:
      - { days: "Mon,Tue,Wed,Thu,Fri,Sat,Sun", start_time: "00:00", end_time: "23:59", url: "https://new.uubloomington.org" }
    signage_browser: 'chromium'
  hosts:
    kiosk1.uubloomington.org