signage_players:
  vars:
    ansible_user: uucb
    signage_schedule:
      - { days: "Mon,Tue,Wed,Thu,Fri,Sat,Sun", start_time: "08:00", end_time: "19:00", url: "http://sanctuary-streamer:8080/22441a1e-28c4-477e-bfea-3a114ff5fa37.html?autoplay=true" }
    signage_browser: 'custom'
    signage_browser_package: 'vlc'
    signage_browser_command: 'vlc '
    signage_browser_window_name: 'vlc'
    signage_browser_execstart_override: 'bash -c \'retry "cvlc --play-and-exit  $(cat /var/ansible-digital-signage/current)"'\''
  hosts:
    display1

kiosks:
  vars:
  ansible_user: uucb
  signage_schedule:
    - { days: "Mon,Tue,Wed,Thu,Fri,Sat,Sun", start_time: "00:00", end_time: "23:59", url: "https://new.uubloomington.org" }
  signage_browser: 'chromium'
  hosts:
    kiosk1