kiosks:
  vars:
    ansible_user: uucb
    signage_schedule:
      - { days: "Mon,Tue,Wed,Thu,Fri,Sat,Sun", start_time: "00:00", end_time: "23:59", url: "https://new.uubloomington.org" }
    signage_browser: 'chromium'
  hosts:
    kiosk1.uubloomington.org