- hosts: signage_players
  become: yes
  roles:
    # - role: 'ansible-role-linux'
    - role: 'ansible_role_signage_player'
  
  tasks:
    - name: Start Pipewire
      ansible.builtin.systemd:
        name: pipewire.service
        state: started
        scope: user
      environment:
        XDG_RUNTIME_DIR: "/run/user/1001"
      become_user: "signage"
      become: true

    - name: Start Pipewire
      ansible.builtin.systemd:
        name: pipewire-pulse.service
        state: started
        scope: user
      environment:
        XDG_RUNTIME_DIR: "/run/user/1001"
      become_user: "signage"
      become: true

    - name: Start Pipewire
      ansible.builtin.systemd:
        name: wireplumber.service
        state: started
        scope: user
      environment:
        XDG_RUNTIME_DIR: "/run/user/1001"
      become_user: "signage"
      become: true

    - name: Ensure certificates directory exists
      ansible.builtin.file:
        path: "/usr/lib64/mozilla/certificates"
        state: directory
        mode: "0665"

    - name: Copy UUCB Internal Root CA
      ansible.builtin.copy:
        src: "uubloomington-intermediate.crt"
        dest: "/usr/lib64/mozilla/certificates/uubloomington-intermediate.crt"

    - name: Install Firefox policies.json
      ansible.builtin.copy:
        src: "policies.json"
        dest: "/usr/lib64/firefox/distribution/policies.json"

- hosts: kiosks
  become: yes
  roles:
    - role: 'ansible_role_signage_player' 
